#!/usr/bin/python3
import sys, os

prog_path = os.path.realpath(os.path.realpath(__file__))
prog_dir  = os.path.dirname(prog_path)
sys.path.insert(0, os.path.join(prog_dir, 'lib'))

from reader import *

basedir = prog_dir
config = Config(basedir=basedir)
app = App(config)

if len(sys.argv) < 2:
    app.help()
    exit(1)
else:
    app.run(sys.argv)
